version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - python3.8 -m venv ~/.venv
      - source ~/.venv/bin/activate
      - make install
      - make lint
      - make test

  build:
    commands:
      - make deploy
  
  post_build:
    commands:
      - echo Build completed on `date`
